[package]
name = "infumap"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.0"
clap = "3.0.10"
config = "0.13.1"
dirs = "4.0"
image = "0.24.5"
kamadak-exif = "0.5.5"
log = "0.4"
pretty_env_logger = "0.4.0"
once_cell = "1.17.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_prometheus = "0.10.0-rc.3"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.89"
sha2 = "0.10.6"
totp-rs = { version = "4.1.0", features = ["qr", "otpauth"] }
uuid = { version = "1.2.1", features = ["v4"] }
