# Copyright (C) 2023 The Infumap Authors
# This file is part of Infumap.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#address = "127.0.0.1"
#port = 8000

#prometheus_address = "127.0.0.1"
#prometheus_port = 9090

#data_dir = "~/.infumap/data"
#cache_dir = "~/.infumap/cache"

# Maximum aggregate size (in megabytes) of all files in the cache.
#cache_max_mb = 500

#max_image_size_deviation_smaller_percent = 30
#max_image_size_deviation_larger_percent = 5

# Whether or not to use the local filesystem to store file and image data.
# You will want to disable this if you are running on a cloud server with
# limited or expensive disk.
#enable_local_object_storage = true

# Primary external object store configuration. If enabled, file and image
# data will be maintained in this AWS S3 compatible object store (in addition
# to other configured object stores). If you are using AWS, you don't need to
# specify an endpoint, only region. If you are using a compatible service, you
# usually only need to specify the endpoint, not region.
#enable_s3_1_object_storage = false
#s3_1_region = 
#s3_1_endpoint = 
#s3_1_bucket = 
#s3_1_key = 
#s3_1_secret = 

# Secondary external object store configuration.
#enable_s3_2_object_storage = false
#s3_2_region = 
#s3_2_endpoint = 
#s3_2_bucket = 
#s3_2_key = 
#s3_2_secret = 

# Database backup configuration. If enabled, the user and item database logs
# will be backed up to the specified AWS S3 compatible object store periodically,
# but only if there have been changes since the last backup. Old backups are
# removed from the object store as new ones are added, unless this would cause
# a gap between historic backups greater than backup_retention_period_days.
# backup_encryption_key must be a 32 byte hex encoded value. Infumap generates
# a unique one automatically for you when it creates a default settings.toml file.
# You can also generate a suitable one manually using the infumap keygen cli command.
#enable_s3_backup = false
#backup_period_minutes = 60
#backup_retention_period_days = 30
#backup_encryption_key = "{{encryption_key}}"
#s3_backup_region = 
#s3_backup_endpoint = 
#s3_backup_bucket = 
#s3_backup_key = 
#s3_backup_secret = 
