# Copyright (C) 2023 The Infumap Authors
# This file is part of Infumap.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# NOTE: Commented out configuration values indicate defaults - you do not
# need to uncomment these lines if you want the default value.


# The level at which to log messages to stderr.
# Only Infumap messages are logged (no messages from dependencies).
# Valid values: off, error, warn, info, debug, trace.
# Infumap currently doesn't emit any messages a trace level.
#log_level = "info"


# The address and port to listen on for web and API requests. Should not be
# exposed to the public internet. Instead, use a reverse proxy and enable
# TLS on it. Refer to the "operations.md" doc file for more information on
# how to deploy Infumap.
#address = "127.0.0.1"
#port = 8000


# Prometheus metrics endpoint configuration. Should not be exposed to the
# public internet. Refer to the "operations.md" doc file for more information.
#enable_prometheus_metrics = false
#prometheus_address = "127.0.0.1"
#prometheus_port = 9090


# The data directory. User and item database logs for each user as well as
# the pending user list are kept in this directory. If you have local
# object storage enabled (the default), file and image data will also be
# stored here. Refer to the "data.md" doc file for more information.
#data_dir = "~/.infumap/data"


# The cache directory. Used to store scaled down images.
#cache_dir = "~/.infumap/cache"

# Maximum aggregate size (in megabytes) of all files in the cache. Files are
# removed using an LRU policy if this size is exceeded.
#cache_max_mb = 500

# Maximum length of time the browser may cache images and files. The maximum
# supported value is one year (31536000 seconds). Set to 0 to specify that
# the browser should not chache Infumap content.
#browser_cache_max_age_seconds = 31536000


# In most instances, full size image data is not required client side, and it
# would be prohibitively expensive to serve full size images whenever an image
# of any size needs to be displayed. On the other hand, there is a relatively
# high cost to creating and maintaining scaled down images on the server.
# First, they need to be fetched from the object store, which may incur an
# egress cost. Then, they need to be scaled, which is relatively
# computationally intensive to do in high qualities. Finally, the image takes
# up space in the server cache. For this reason, Infumap can be configured to
# serve images that are different from the requested size, if they are already
# present in the cache. The following properties specify the maximum amount an
# image may be scaled up or down browser side.
#max_scale_image_down_percent = 50
#max_scale_image_up_percent = 0


# Whether or not to use the local filesystem to store file and image object
# data. You will want to disable this if you are running on a cloud server with
# limited or expensive disk.
#enable_local_object_storage = true

# Primary external object store configuration. If enabled, file and image
# data will be maintained in this AWS S3 compatible object store (in addition
# to other configured object stores). If you are using AWS, you don't need to
# specify an endpoint, only region. If you are using a compatible service, you
# usually only need to specify the endpoint, not region.
#enable_s3_1_object_storage = false
#s3_1_region = 
#s3_1_endpoint = 
#s3_1_bucket = 
#s3_1_key = 
#s3_1_secret = 

# Secondary external object store configuration. Objects will be read from the
# pimary object store by default - the secondary is only used as a backup in case
# of error. For this reason, you should use the vendor with the lowest egress
# cost for the primary store.
#enable_s3_2_object_storage = false
#s3_2_region = 
#s3_2_endpoint = 
#s3_2_bucket = 
#s3_2_key = 
#s3_2_secret = 


# Database backup configuration. If enabled, the user and item database logs
# will be backed up to the specified AWS S3 compatible object store periodically,
# but only if there have been changes since the last backup. Old backups are
# removed from the object store as new ones are added, unless this would cause
# a gap between historic backups greater than backup_retention_period_days.
# backup_encryption_key must be a 32 byte hex encoded value. Infumap generates
# a unique one automatically for you when it creates a default settings.toml file.
# You can also generate a suitable one manually using the infumap keygen cli command.
#enable_s3_backup = false
#backup_period_minutes = 60
#backup_retention_period_days = 30
#backup_encryption_key = "{{encryption_key}}"
#s3_backup_region = 
#s3_backup_endpoint = 
#s3_backup_bucket = 
#s3_backup_key = 
#s3_backup_secret = 
