[package]
name = "infusdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
uuid = { version = "1.2.1", features = ["v4"] }
serde = { version = "1.0.151", features = ["derive"] }